"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Ortam değişkeninden oku; yoksa (sadece geliştirme için) yedek değer kullan.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-of4wn11wb#e@f*^@(q_!n%a+vjdaw%i8j$l!cy1v-o(nap@c-y',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Production'da DEBUG=False olacak şekilde ortam değişkeni kullan (örn. DEBUG=0 veya atama yok).
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes') #'true' , '1', 'yes'

# Örn: ALLOWED_HOSTS=example.com,api.example.com
ALLOWED_HOSTS = (
    [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]
    if not DEBUG
    else ['*']
)


# Application definition

INSTALLED_APPS = [
    # Django Çekirdek Modülleri
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

# Senin Uygulamaların
    'users',
    'store',


    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',

    # 3. Parti Kütüphaneler (Auth & API)
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',


]

SITE_ID = 1

# --- Auth & "Beni Hatırla" Yapılandırması ---
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'my-app-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'my-refresh-token',
    'JWT_AUTH_HTTPONLY': True,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
}

# 30 Günlük Oturum Süresi
ACCOUNT_SESSION_REMEMBER = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30

# Email Odaklı Giriş Ayarları
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = os.environ.get('ACCOUNT_EMAIL_VERIFICATION', 'optional')


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Google Allauth için gereken kritik satır burası:
    'allauth.account.middleware.AccountMiddleware',

]

AUTHENTICATION_BACKENDS = [
    # Django'nun kendi admin girişi için
    'django.contrib.auth.backends.ModelBackend',
    # Allauth ile sosyal girişler için
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Sosyal hesap ayarları (Hatanın detayı için ekliyoruz)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# Çakışmaları önlemek için ek ayarlar
SOCIALACCOUNT_AUTO_SIGNUP = True  # Kullanıcı yoksa otomatik oluştur
SOCIALACCOUNT_LOGIN_ON_GET = False

ROOT_URLCONF = 'core.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

from decouple import config, Csv

# core/settings.py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Bu satır Django'ya "Postgres kullanıyorsun" der.
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}
CORS_ALLOWED_ORIGINS = [
    o for o in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if o
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = (
    [o for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o]
    if not DEBUG
    else []
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Kullanıcıyı 30 gün boyunca hatırla
ACCOUNT_SESSION_REMEMBER = True
SESSION_COOKIE_AGE = 2592000 # 30 gün (saniye)

# Sosyal hesapla giriş yapıldığında otomatik kayıt ve giriş
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'users.User'

# Google Allauth: Giriş sonrası önce JWT üretilir, sonra frontend'e yönlendirilir
LOGIN_REDIRECT_URL = '/api/auth/google-jwt-redirect/'
# Frontend'de token'ların yazılacağı sayfa (hash ile access & refresh alır)
FRONTEND_AUTH_CALLBACK_URL = os.environ.get('FRONTEND_AUTH_CALLBACK_URL', 'http://localhost:5173/auth/callback')
# Çıkış sonrası frontend ana sayfa
LOGOUT_REDIRECT_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Eğer allauth profil sayfasına gitmeye zorlarsa bunu kapatıyoruz
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'

SOCIALACCOUNT_STORE_TOKENS = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'allauth': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
