# Generated by Django 5.2.10 on 2026-02-04 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d_poster',
            field=models.ImageField(blank=True, help_text='3D model için önizleme/poster görseli', null=True, upload_to='products/model_posters/'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='products/models/', validators=[django.core.validators.FileExtensionValidator(['glb', 'gltf', 'usdz'])]),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'size', 'color'), name='unique_cart_item'),
        ),
    ]
